//
//  DummyModels.swift
//  iOS-Test
//

enum DummyModels {
  // Models for "load (list)" use case
  struct Load {
    // Request is passed to Interactor
    struct Request {
      
    }
    // Response is passed from Interactor to Presenter
    struct Response {
      
    }
    // View model is generated by Presenter and passed to View
    struct ViewModel {
      
    }
  }
  
  // Add more use cases here
}
